### ISSUE TITLE
New patch version release

### ISSUE THREAD

**Issue by kruton** [vRallev/ECC-25519#7]
The EdDSA library that was updated in #6 includes the encoding and decoding of EdDSA keys, so releasing a new version of this library would pull in that functionality.

**Comment by vRallev** [comment]
I'll try to find some time over the weekend!

**Comment by kruton** [comment]
Any assistance needed to complete this?

**Comment by vRallev** [comment]
I released version 1.0.2. Please give it a try and let me know if everything works as expected.

I'm sorry for the long delay!
